### ISSUE TITLE
IntranetUserJS: Hide patrons' protected radio buttons

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-hide-patron-protected#1]
IntranetUserJS: Hide patrons' protected radio buttons
Hides patrons' Protected radio buttons from non-superlibrarians

Testaus:

Poista rimpsu // Asiakastietojen suojattu-valinnan piilotus intranetUserJS-asetuksesta
Aktivoi plugin
Testaa, että asiakastilin Suojattu-valinta ei näy kuin superlibrarianina kirjautuneena

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa intranetuserJS-rimpsu poistettu ja plugin otettu käyttöön:

- [ ] Lappi
- [ ] OUTI
- [ ] Siili
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Lastu
- [ ] Vaski

**Comment by ReettaSiili** [comment]
Tämä js ei ollut Siilissä ennestään, mutta nyt kun aktivoin plugarin, niin toimii oikein supervirkailijalla ja tavallisella virkailijalla.

**Comment by pirliis** [comment]
OUTIssa näyttää toimivan, vain superlibrarian oikeuksilla Suojattu-valinta on näkyvillä.

**Comment by ElinaUotila** [comment]
Kirkesissä aktivoitu ja toimii oikein.

**Comment by AnneliO** [comment]
Tämä on nyt kaikilla kuosissa. Suljen tiketin.
